version: "3.8"
services:
  app:
    build:
      context: .
      target: production
    environment:
      - PORT_APP=3000
      - WORKERS=2
      - ASYNC_CORES=2000
      - PROTOCOL=http
    env_file:
      - .env
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:6-alpine
    restart: on-failure
    volumes:
      - "redis-data:/data"

  postgres:
    image: postgres:14
    restart: on-failure
    volumes:
      - "postgres-data:/var/lib/postgresql"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: auth_db

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app

volumes:
  redis-data:
    driver: "local"
  postgres-data:
    driver: "local"
